#pragma once
#include <iostream>
#include <vector>
#include <windows.h>
#include <TlHelp32.h>
#include <memory>
#include <string_view>
#include <map>
#include <cstdint>
#include <stdexcept>
#include "obfuscate.hpp"